#:kivy 1.11.0
#:import Window kivy.core.window.Window
<CommentsManager>:
    orientation: 'vertical'
    comments_box: comments_box
    comment_input: comment_input
    GridLayout:
        cols: 1
        rows: 2
        # orientation: 'vertical'
        # size_hint_y: None
        size: root.size
        BoxLayout:
            canvas.before:
                Color:
                    #dark green
                    rgba: 0.5, 0, 0.1, 1
                Rectangle:
                    pos: self.pos
                    size: self.size

            ScrollView:
                pos: self.pos
                scroll_y: 1
                scroll_type: ['bars', 'content']
                do_scroll_x: False
                do_scroll_y: True
                # size_hint_y: self.height
                # fill parent
                # height: root.height
                size: root.size
                GridLayout:
                    cols: 1
                    size_hint_y: None
                    height: self.minimum_height
                    id: comments_box
                    padding: 1
                    spacing: 1
            # add comments and back button
            # Add new comment
        BoxLayout:
            size_hint: 1, 0.3
            orientation: 'horizontal'
            padding: 10, 10
            spacing: 10
            TextInput:
                id: comment_input
                multiline: True
                hint_text: 'Add comment'
                background_color: 0, 0, 0, 1
                foreground_color: 1, 1, 1, 1
                font_size: 20
                padding: 10, 10
            Button:
                text: 'Add'
                on_press: root.add_comment(comment_input.text)
                background_color: 0, 0, 1, 1
                foreground_color: 1, 1, 1, 1
                font_size: 20
                size_hint: 0.2, 1
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                canvas.before:
                    Color:
                        rgba: 0, 0, 1, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
            # Back button
            Button:
                text: 'Back'
                on_press: root.manager.current = 'main'
                # light green
                background_color: 0, 1, 0, 1
                foreground_color: 1, 1, 1, 1
                font_size: 20
                size_hint: 0.2, 1
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                canvas.before:
                    Color:
                        rgba: 0, 0, 1, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
            Button:
                text: 'Delete'
                on_press: root.delete_comment()
                # red
                background_color: 1, 0, 0, 1
                foreground_color: 1, 1, 1, 1
                font_size: 20
                size_hint: 0.2, 1
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
<Comment@Button>:
    size_hint_y: None
    height: self.texture_size[1]
    text_size: self.width, None
    valign: 'top'
    halign: 'left'
    padding_x: 5
    padding_y: 5
    markup: True
    # blue Color
    background_color: 0, 0, 1, 1
    color: 1, 1, 1, 1
    # on_press: self.parent.parent.parent.