#:kivy 1.11.0
<MenuBar>:
    height: self.minimum_height
    orientation: 'vertical'
    size_hint: 1, None
    tree_view_drop: tree_view_drop
    actions_drop: actions_drop.__self__
    ActionBar:
        size : root.width, 40
        pos: 0, root.height - self.height
        # lime background color
        background_color: 0.678, 1, 0.184, 1
        ActionView:
            use_separator: True
            ActionPrevious:
                font_size: 130
                # bold
                font_name: 'Comic Sans MS'
                title: 'SciLibra'
                # color red
                background_color: 1, 0, 0, 1
                with_previous: False
                app_icon: 'icon_main.png'
            # ActionButton:
            #     text: 'help'
            #     # open small dialog with help
            #     on_release: root.show_help()
            ActionButton:
                text: 'Quit'
                on_release: app.stop()
            ActionButton:
                text: 'About'
                # create a dropdown menu
                on_press: root.show_about()
            ActionButton:
                text: 'Tree view'
                on_release: tree_view_drop.open(self)
                DropDown:
                    id: tree_view_drop
                    size_hint: None, None
            ActionButton:
                text: 'Load'
                on_release: root.show_load()
            ActionButton:
                text: 'Actions'
                on_release: actions_drop.open(self)
                DropDown:
                    id: actions_drop
                    auto_width: False
                    width: 200
                    Button:
                        text: 'Update Paths'
                        size_hint: None, None
                        height: 44
                        width: 200
                        on_release: root.updatefolderpath()
                    Button:
                        text: 'Filter Database'
                        size_hint: None, None
                        height: 44
                        width: 200
                        on_release: root.filter_database()
                    Button:
                        text: 'Save Database as BibTex'
                        size_hint: None, None
                        height: 44
                        width: 200
                        on_release: root.save_database_as_bibtex()
                    Button:
                        # search for articles
                        text: 'Search'
                        size_hint: None, None
                        height: 44
                        width: 200
                        on_release: root.search_article()
                    Button:
                        text: 'Add Article'
                        size_hint: None, None
                        height: 44
                        width: 200
                        on_release: root.add_article()
                    Button:
                        text: 'Delete Article'
                        size_hint: None, None
                        height: 44
                        width: 200
                        on_release: root.delete_article()
                    Button:
                        text: 'Delete All Articles'
                        size_hint: None, None
                        height: 44
                        width: 200
                        on_release: root.delete_all_articles()
            ActionButton:
                text: 'Statistics'
                on_release: stats_drop.open(self)
                DropDown:
                    id: stats_drop
                    auto_width: False
                    width: 200
                    Button:
                        text: 'General Statistics'
                        size_hint: None, None
                        height: 44
                        width: 200
                        on_release: root.general_statistics()
                    Button:
                        text: 'Articles with no PDF'
                        size_hint: None, None
                        height: 44
                        width: 200
                        on_release: root.articles_with_no_pdf()
            # empty action item to fill the space
            ActionButton:
                text: ''
                size_hint_x: 0.5