#:kivy 1.11.0
<SaveDialog>:
    size_hint: None, None  # Keeps the dialog box from going full screen
    size: 400, 200
    title: 'Save file'
    auto_dismiss: False

    BoxLayout:
        orientation: "vertical"
        size: root.size
        pos: root.pos

        TextInput:
            id: file_name
            text: 'SciLibra.bib'
            multiline: False
            size_hint_y: 0.1
            on_focus: if self.focus and self.text == 'SciLibra.bib': self.text = ''
            background_color: 0.8, 0.8, 0.8, 1

        FileChooserListView:
            id: filechooser
            filters: ['*.bib']
            size_hint_y: 0.8  # Fill remaining space

        GridLayout:
            cols: 2
            size_hint_y: 0.1
            height: 30

            Button:
                text: "Cancel"
                on_release: root.cancel()
            
            Button:
                text: "Save"
                on_release: root.save(filechooser.path, file_name.text)